name: Create PRs from dev to feature branches after pushing to dev

on:
  #push:
    #branches:
      #- dev
  pull_request:
    types: 
      - closed
    branches:
      - dev

jobs:
  create-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get triggering branch
        id: get_branch
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
          
      - name: Read output
        run: echo "branch=${{ steps.get_branch.outputs.branch }}"

      - name: Get branch list minus main and dev
        id: get_branches
        run: |
          git fetch origin --prune
          git branch -r | grep -Ev '.*main|dev.*' | sed 's|origin/||g' | sed 's| *||g' | tr '\n' ' ' | sed -E 's| $||'
          echo "branches=$(git branch -r | grep -Ev '.*main|dev.*' | sed 's|origin/||g' | sed 's| *||g' | tr '\n' ' ' | sed -E 's| $||')" >> "$GITHUB_OUTPUT"
          
      - name: Read output
        run: echo "branches=${{ steps.get_branches.outputs.branches }}"

      - name: Create PRs
        env:
         GH_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
        run: |
          for branch in ${{ steps.get_branches.outputs.branches }}; do
            if [ "$branch" != "${{ steps.get_branch.outputs.branch }}" ]; then
              pr_exist=$(gh pr list --state open --head "dev:$branch" --json number | jq 'length')
              echo "pr_exists=$pr_exists"
              if [[ -n "$pr_exist" && "$pr_exist" -eq 0 ]]; then
                gh pr create --title "Merge dev into $branch" --body "This PR automatically merges changes from dev into $branch." --base $branch --head dev
              fi
            fi
          done
