name: Create PRs from dev to feature branches after pushing to dev

on:
  pull_request:
    types: 
      - closed

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - name: read
        run: |
          echo "${{ github.event.pull_request.merged }}"
          echo "${{ github.event.pull_request.merged }} && echo true || echo false"
          echo base.ref
          echo "${{ github.event.pull_request.base.ref }}"
          echo head.ref
          echo "${{ github.event.pull_request.head.ref }}"
  
  create-prs:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get triggering branch
        id: get_branch
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Get branch list minus main and dev
        id: get_branches
        run: |
          git fetch origin --prune
          git branch -r | grep -Ev '.*main|dev.*' | sed 's|origin/||g' | sed 's| *||g' | tr '\n' ' ' | sed -E 's| $||'
          echo "branches=$(git branch -r | grep -Ev '.*main|dev.*' | sed 's|origin/||g' | sed 's| *||g' | tr '\n' ' ' | sed -E 's| $||')" >> "$GITHUB_OUTPUT"
          
      - name: Create PRs
        env:
         GH_TOKEN: ${{ secrets.ACTION_TOKEN_LOCAL_REPO_SECRET }}
        run: |
          for branch in ${{ steps.branches_minus_dev_main.outputs.branches }}; do
          
            # Only proceed if this is not the triggering branch
            if [ "$branch" != "${{ steps.triggering_branch.outputs.branch }}" ]; then
              
              # Create a PR from dev to $branch unless one already exists
              if ! gh pr list --state open --head dev --json author,number,headRefName,baseRefName,changedFiles | jq -r '.[].baseRefName' | grep -q $branch ; then
                gh pr create --title "Merge dev into $branch" \
                             --body "This PR was automatically created to propose changes from dev into $branch." \
                             --base $branch \
                             --head dev
              fi
            fi
          done
