name: Create PRs from dev to feature branches after pushing to dev

on:
  #push:
    #branches:
      #- dev
  pull_request:
    types: 
      - closed
    branches:
      - dev

jobs:
  create-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get triggering branch
        id: get_branch
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Get branch list minus main and dev
        id: get_branches
        run: |
          git fetch origin --prune
          git branch -r | grep -Ev '.*main|dev.*' | sed 's|origin/||g' | sed 's| *||g' | tr '\n' ' ' | sed -E 's| $||'
          echo "branches=$(git branch -r | grep -Ev '.*main|dev.*' | sed 's|origin/||g' | sed 's| *||g' | tr '\n' ' ' | sed -E 's| $||')" >> "$GITHUB_OUTPUT"
          
      - name: Create PRs
        env:
         GH_TOKEN: ${{ secrets.ACTION_TOKEN_LOCAL_REPO_SECRET }}
        run: |
          for branch in ${{ steps.get_branches.outputs.branches }}; do
            echo "branch=$branch"
            if [ "$branch" != "${{ steps.get_branch.outputs.branch }}" ]; then
              echo branch is different
              pr_exist=$(gh pr list --state open --head dev --json author,number,headRefName,baseRefName,changedFiles | jq -r '.[].baseRefName' | grep -q $branch)
              echo "pr_exists=$pr_exists"
              gh pr list --state open --head dev --json author,number,headRefName,baseRefName,changedFiles | jq -r '.[].baseRefName' | grep -q $branch && echo yes || echo no
              if [[ gh pr list --state open --head dev --json author,number,headRefName,baseRefName,changedFiles | jq -r '.[].baseRefName' | grep -q $branch ]]; then
                gh pr create --title "Merge dev into $branch" \
                             --body "This PR was automatically created to propose changes from dev into $branch." \
                             --base $branch \
                             --head dev
              fi
            fi
          done
